/**
 * Example 2 using xjc-generated class from xsd schema, and JAXB mapping
 * 
 * http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.xsd
 * 
 * launch in src\main\java\ :
 * xjc -p j2ee.mvn.war.c.amazon2 j2ee\mvn\war\c\amazon2\xsd\AWSECommerceService.xsd
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package j2ee.mvn.war.c.amazon2;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2016.09.24 at 03:34:49 AM CEST 
//



